### ISSUE TITLE
Celery Message Protocol Version 2 Support?

### ISSUE THREAD

**Issue by gushitong** [gocelery/gocelery#35]
Celery Message Protocol: 
http://docs.celeryproject.org/en/latest/internals/protocol.html

```bash
[2018-06-21 14:55:50,898: INFO/MainProcess] Received task: injection.data_sync.tasks.write_to_es[2494885c-0361-4be9-9635-c2d578dec026]  ETA:[2018-06-21 14:55:50+08:00] 
[2018-06-21 14:55:50,899: DEBUG/MainProcess] basic.qos: prefetch_count->20
[2018-06-21 14:55:50,900: ERROR/MainProcess] Error in timer: TypeError("'NoneType' object is not iterable",)
Traceback (most recent call last):
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/kombu/asynchronous/hub.py", line 136, in fire_timers
    entry()
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/kombu/asynchronous/timer.py", line 68, in __call__
    return self.fun(*self.args, **self.kwargs)
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 482, in apply_eta_task
    self.on_task_request(task)
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/celery/worker/worker.py", line 223, in _process_task_sem
    return self._quick_acquire(self._process_task, req)
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/kombu/asynchronous/semaphore.py", line 62, in acquire
    callback(*partial_args, **partial_kwargs)
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/celery/worker/worker.py", line 228, in _process_task
    req.execute_using_pool(self.pool)
  File "/Users/gushitong/.virtualenvs/gaia/lib/python2.7/site-packages/celery/worker/request.py", line 520, in execute_using_pool
    time_limit, soft_time_limit = self.time_limits
TypeError: 'NoneType' object is not iterable
```

Celery 4.2(Consumer) will crash if receive task from `gocelery` due to Message Protocol Mismatch.

**Comment by sickyoon** [comment]
I am working on supporting message protocol v2

**Comment by sanghinitin** [comment]
i have created a solution for this using https://github.com/streadway/amqp direct implementation. But it not as per complete.
`// Returns a pointer to a new task header object
func NewHeader(id string ,task string) (amqp.Table) {
	t := make(amqp.Table)
	t["task"] = task
	t["lang"] = "py"
	t["id"] = id
	t["root_id"] = id
	return t
}


func NewBody(args []interface{}, kwargs map[string]interface{}) ([]byte, error){
	var a []interface{}
	a = append(a, args)
	a = append(a, kwargs)
	a = append(a, nil)
	return json.Marshal(a)
}


func (c * CeleryClient) sendTask(task string, args []interface{},  kwargs map[string]interface{})(err error){
	id, err := uuid.NewV4()
	if err != nil {
		return err
	}
	q, err := c.Channel.QueueDeclare(
		"celery", // name
		true,   // durable
		false,   // delete when unused
		false,   // exclusive
		false,   // no-wait
		nil,     // arguments
	)
	if err != nil {
		return err
	}
	body,err := NewBody(args, kwargs)
	if err != nil{
		return err
	}
	header := NewHeader(id.String(),task)
	err = c.Channel.Publish(
		"celery",     // exchange
		q.Name, // routing key
		false,  // mandatory
		false,  // immediate
		amqp.Publishing{
			Headers:header,
			Body:        []byte(body),
			ContentEncoding:"utf-8",
			ContentType: "application/json",
			CorrelationId:id.String(),
			DeliveryMode:amqp.Persistent,
			Priority:0,
		})
	if err != nil{
		return err

	}
	return
}`

it is completing my requirement

**Comment by vitormhenrique** [comment]
Was anyone able to update the library to work with the protocol 2?
