### ISSUE TITLE
gocelery client crashes python celery workers (python 3.6, celery 4.2.1, redis broker/backend)

### ISSUE THREAD

**Issue by JJ** [gocelery/gocelery#96]
I'm trying this Go client:
```
package main

import (
	"os"
	"fmt"
	"github.com/gocelery/gocelery"
	"math/rand"
)

func main() {
	// initialize celery client
	url := fmt.Sprintf("amqp://platzi:%s@localhost/platzi",os.Getenv("RMQ_PASS"))
	cli, _ := gocelery.NewCeleryClient(
		gocelery.NewAMQPCeleryBroker(url),
		gocelery.NewAMQPCeleryBackend(url),
		1,
	)

	// Prepara los comandos
	taskName := "RegistraComandos.registra"
	comandos := [3]string{"uno","dos","tres"}
	
	i:= 0
	for i < 1 {
		_, err := cli.Delay(taskName, comandos[rand.Intn(3)])
		if err != nil {
			panic(err)
		}
	}
}
```

But it crashes the Python worker with this error:
```
[2019-03-06 10:23:31,621: CRITICAL/MainProcess] Unrecoverable error: AttributeError("'NoneType' object has no attribute 'tzinfo'",)
Traceback (most recent call last):
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/worker.py", line 205, in start
    self.blueprint.start(self)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 317, in start
    blueprint.start(self)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 593, in start
    c.loop(*c.loop_args())
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/loops.py", line 88, in asynloop
    update_qos()
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kombu/common.py", line 417, in update
    return self.set(self.value)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kombu/common.py", line 410, in set
    self.callback(prefetch_count=new_value)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/consumer/tasks.py", line 47, in set_prefetch_count
    apply_global=qos_global,
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kombu/messaging.py", line 558, in qos
    apply_global)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/channel.py", line 1812, in basic_qos
    wait=spec.Basic.QosOk,
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/abstract_channel.py", line 59, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/abstract_channel.py", line 79, in wait
    self.connection.drain_events(timeout=timeout)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/connection.py", line 491, in drain_events
    while not self.blocking_read(timeout):
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/connection.py", line 497, in blocking_read
    return self.on_inbound_frame(frame)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/method_framing.py", line 77, in on_frame
    callback(channel, msg.frame_method, msg.frame_args, msg)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/connection.py", line 501, in on_inbound_method
    method_sig, payload, content,
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/abstract_channel.py", line 128, in dispatch_method
    listener(*args)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/amqp/channel.py", line 1597, in _on_basic_deliver
    fun(msg)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/kombu/messaging.py", line 624, in _receive_callback
    return on_m(message) if on_m else self.receive(decoded, message)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 567, in on_task_received
    callbacks,
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/strategy.py", line 153, in task_message_handler
    body=body, headers=headers, decoded=decoded, utc=utc,
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/worker/request.py", line 140, in __init__
    self.eta = maybe_make_aware(eta, self.tzlocal)
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/utils/time.py", line 327, in maybe_make_aware
    if is_naive(dt):
  File "/home/jmerelo/.pyenv/versions/3.6.1/lib/python3.6/site-packages/celery/utils/time.py", line 282, in is_naive
    return dt.tzinfo is None or dt.tzinfo.utcoffset(dt) is None
AttributeError: 'NoneType' object has no attribute 'tzinfo'
```

That particular worker works like a charm with Python and also node-celery clients, so far.

**Comment by sickyoon** [comment]
Please provide following information when reporting bug:

* celery version
* broker type & version
* backend type & version

**Comment by JJ** [comment]
Celery: celery --version
4.2.1 (windowlicker)
Broker & backend: RabbitMQ       {rabbit,"RabbitMQ","3.7.12"},

**Comment by sickyoon** [comment]
Okay, I tracked down the issue. Above error is due to ETA being set as empty string whereas celery worker is expecting it to be null.

**Comment by sickyoon** [comment]
Fix merged: https://github.com/gocelery/gocelery/pull/97
@JJ can you try again and let me know so I can close this issue?

**Comment by JJ** [comment]
OK, I'll give it a try. Do we need to set protocol version also to one?

**Comment by sickyoon** [comment]
yes

**Comment by sickyoon** [comment]
This has been verified on my end. Closing.
